# Generated by Django 4.0.2 on 2023-03-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0002_remove_progress_report_section_daily_work_cl_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_report',
            name='cl_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
