# Generated by Django 4.0.2 on 2023-03-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0004_rename_daily_file_daily_work_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_asign',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.client_information'),
        ),
    ]
