# Generated by Django 4.0.2 on 2023-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0008_daily_work_diry_daily_work_diry_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='art',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='art_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='art_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='bk',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='bk_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='bk_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='blg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='blg_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='blg_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='clss',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='clss_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='clss_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='gst',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='gst_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='gst_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pr',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pr_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pr_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
