# Generated by Django 4.0.2 on 2023-04-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0013_smo_registration_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_registration',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.client_information'),
        ),
    ]
