# Generated by Django 4.0.2 on 2023-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0015_smo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_post',
            name='status',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
