# Generated by Django 4.0.2 on 2023-04-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0017_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_information',
            name='am_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='cm_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='em_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='mm_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='off_pg_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='on_pg_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='sem_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='seo_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='smm_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='smo_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='vm_target',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
