# Generated by Django 4.0.2 on 2023-04-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0021_remove_events_end_events_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(null=True)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
