# Generated by Django 4.0.2 on 2023-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0023_remove_correction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='img',
        ),
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
