# Generated by Django 4.0.2 on 2023-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0032_smo_post_date_smo_post_diry_dt_smo_post_diry_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smo_post',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='diry_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='fb_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='insta_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='link_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='pin_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='qra_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='sbms_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='tumb_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='tw_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='yt_dt',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
