# Generated by Django 4.0.2 on 2023-05-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0033_alter_smo_post_date_alter_smo_post_diry_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addi_smo_post',
            old_name='sbms_dt',
            new_name='date',
        ),
        migrations.AddField(
            model_name='addi_smo_post',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
