# Generated by Django 4.0.2 on 2023-05-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0036_alter_smo_post_diry_dt_alter_smo_post_fb_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smo_post',
            name='diry_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='fb_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='insta_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='link_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='pin_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='qra_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='sbms_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='tumb_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='tw_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smo_post',
            name='yt_dt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
