# Generated by Django 4.0.2 on 2023-05-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0037_alter_smo_post_diry_dt_alter_smo_post_fb_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smo_post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
