# Generated by Django 4.0.2 on 2023-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0039_smo_post_diry_smo_post_fb_smo_post_insta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_post',
            name='st_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
    ]
