# Generated by Django 4.0.2 on 2023-05-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0048_rename_leeds_client_information_lc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_leeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_txt', models.TextField(blank=True, default='', null=True)),
                ('sub_file', models.ImageField(blank=True, null=True, upload_to='images/sub/')),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.daily_work')),
            ],
        ),
    ]
