# Generated by Django 4.0.2 on 2023-03-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress_report',
            name='section',
        ),
        migrations.AddField(
            model_name='daily_work',
            name='cl_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.TextField(null=True)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
