# Generated by Django 4.0.2 on 2023-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0003_progress_report_cl_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_work',
            old_name='daily_file',
            new_name='json',
        ),
        migrations.AddField(
            model_name='daily_work',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, default='', null=True),
        ),
    ]
