# Generated by Django 3.2.19 on 2023-07-11 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0003_alter_daily_leeds_exists_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_leeds_exists',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
        migrations.CreateModel(
            name='he_daily_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('workdone', models.TextField(blank=True, default='', null=True)),
                ('json', models.FileField(blank=True, default='', null=True, upload_to='images/pdf/')),
                ('json_testerscreenshot', models.JSONField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
