# Generated by Django 4.0.2 on 2023-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0005_work_asign_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_information',
            name='off_pg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='off_pg_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/requirement/'),
        ),
        migrations.AddField(
            model_name='client_information',
            name='off_pg_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='on_pg',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='on_pg_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/requirement/'),
        ),
        migrations.AddField(
            model_name='client_information',
            name='on_pg_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
