# Generated by Django 4.0.2 on 2023-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0006_client_information_off_pg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_information',
            name='smo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client_information',
            name='smo_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/requirement/'),
        ),
        migrations.AddField(
            model_name='client_information',
            name='smo_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='file_2',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/pdf/'),
        ),
    ]
