# Generated by Django 4.0.2 on 2023-03-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0007_client_information_smo_client_information_smo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='diry',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='diry_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='diry_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='fb_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='fb_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='insta',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='insta_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='insta_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='link_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='link_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pin_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='pin_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='qra',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='qra_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='qra_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='sbms',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='sbms_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='sbms_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tumb',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tumb_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tumb_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tw',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tw_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='tw_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='yt',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='yt_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/sub/'),
        ),
        migrations.AddField(
            model_name='daily_work',
            name='yt_txt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='daily_work_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_txt', models.TextField(blank=True, default='', null=True)),
                ('sub_file', models.ImageField(blank=True, null=True, upload_to='images/sub/')),
                ('daily', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.daily_work')),
            ],
        ),
    ]
