# Generated by Django 4.0.2 on 2023-04-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0012_smo_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_registration',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
