# Generated by Django 4.0.2 on 2023-04-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0014_smo_registration_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='smo_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('json', models.FileField(blank=True, default='', null=True, upload_to='images/smo_post/')),
                ('json_testerscreenshot', models.JSONField(blank=True, default='', null=True)),
                ('smo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.smo_registration')),
            ],
        ),
    ]
