# Generated by Django 4.0.2 on 2023-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0019_addi_client_info_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
