# Generated by Django 4.0.2 on 2023-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0020_work_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
    ]
