# Generated by Django 4.0.2 on 2023-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0024_remove_events_img_events_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
    ]
