# Generated by Django 4.0.2 on 2023-04-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0025_remove_events_end_events_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration'),
        ),
    ]
