# Generated by Django 4.0.2 on 2023-04-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0026_events_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='daily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.daily_work'),
        ),
    ]
