# Generated by Django 4.0.2 on 2023-04-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0027_correction_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_post',
            name='executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration'),
        ),
    ]
