# Generated by Django 4.0.2 on 2023-04-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0029_daily_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
