# Generated by Django 4.0.2 on 2023-04-28 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0031_events_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_post',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='diry_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='diry_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='fb_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='fb_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='insta_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='insta_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='link_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='link_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='pin_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='pin_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='qra_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='qra_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='sbms_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='sbms_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tumb_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tumb_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tw_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tw_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='yt_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='yt_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/smo_post/'),
        ),
        migrations.CreateModel(
            name='addi_smo_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbms_dt', models.DateTimeField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/smo_post/')),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.smo_post')),
                ('smo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.smo_registration')),
            ],
        ),
    ]
