# Generated by Django 4.0.2 on 2023-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0034_rename_sbms_dt_addi_smo_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addi_smo_post',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
