# Generated by Django 4.0.2 on 2023-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0038_alter_smo_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='smo_post',
            name='diry',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='fb',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='insta',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='qra',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='sbms',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tumb',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='tw',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smo_post',
            name='yt',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
