# Generated by Django 4.0.2 on 2023-05-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0049_daily_leeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.events'),
        ),
    ]
