# Generated by Django 4.0.2 on 2023-06-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0051_all_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_leads',
            name='year_of_passout',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
