# Generated by Django 4.0.2 on 2023-06-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0052_alter_all_leads_year_of_passout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_leeds',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='daily_leeds',
            name='sub_file',
        ),
        migrations.RemoveField(
            model_name='daily_leeds',
            name='sub_txt',
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='collegename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='email_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='fresher_experience',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='internship',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='internship_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='internship_institute',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='internship_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='internship_topic',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='ph_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='previous_experience',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='register',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_leeds',
            name='year_of_passout',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
