# Generated by Django 4.0.2 on 2023-06-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0054_all_leads_duration_daily_leeds_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_leads',
            name='data_manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='all_leads',
            name='telecaller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='am_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='cm_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='em_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='lc_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='mm_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='off_pg_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='on_pg_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='sem_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='seo_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='smm_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='smo_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='vm_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
