# Generated by Django 4.0.2 on 2023-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0055_all_leads_data_manager_id_all_leads_telecaller_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
