# Generated by Django 4.0.2 on 2023-06-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0056_daily_work_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('leave_status', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('designation_id', models.CharField(max_length=200)),
                ('leaveapprovedstatus', models.CharField(default='0', max_length=200)),
                ('leave_rejected_reason', models.CharField(max_length=300)),
                ('days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveuser', to='DMcoreapp.user_registration')),
            ],
        ),
    ]
