# Generated by Django 4.0.2 on 2023-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0057_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='delay',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
