# Generated by Django 4.0.2 on 2023-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0058_work_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
