# Generated by Django 4.1.7 on 2023-06-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DMcoreapp", "0060_all_leads_ex_duration_daily_leeds_ex_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead_assign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telecaller", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "checkbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DMcoreapp.all_leads",
                    ),
                ),
            ],
        ),
    ]
