# Generated by Django 4.1.7 on 2023-06-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DMcoreapp", "0061_lead_assign"),
    ]

    operations = [
        migrations.DeleteModel(name="Lead_assign",),
    ]
