# Generated by Django 4.1.7 on 2023-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DMcoreapp", "0064_remove_all_leads_ex_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_leads",
            name="ex_duration",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
