# Generated by Django 4.1.7 on 2023-06-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DMcoreapp", "0065_all_leads_ex_duration"),
    ]

    operations = [
        migrations.DeleteModel(name="Lead_assign",),
    ]
