# Generated by Django 4.1.4 on 2023-06-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0067_lead_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='lead_delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('achived', models.IntegerField(blank=True, default=0, null=True)),
                ('sub_target', models.IntegerField(blank=True, default=0, null=True)),
                ('executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMcoreapp.user_registration')),
            ],
        ),
    ]
